# Form implementation generated from reading ui file 'UI/createAccount.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 690)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 900))
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: skyblue;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 120, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(120, 140, 471, 31))
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"    background-color: #e5e7eb;      /* light gray */\n"
"    color: #111827;\n"
"    border: 1px solid #d1d5db;\n"
"    border-radius: 12px;            /* smooth border */\n"
"    padding: 8px 10px;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"/* when focused */\n"
"QLineEdit:focus {\n"
"    background-color: #f3f4f6;\n"
"    border: 1px solid #6b7280;\n"
"}\n"
"\n"
"/* disabled */\n"
"QLineEdit:disabled {\n"
"    background-color: #d1d5db;\n"
"    color: #9ca3af;\n"
"}\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 210, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(370, 230, 221, 31))
        self.lineEdit_2.setStyleSheet("QLineEdit {\n"
"    background-color: #e5e7eb;      /* light gray */\n"
"    color: #111827;\n"
"    border: 1px solid #d1d5db;\n"
"    border-radius: 12px;            /* smooth border */\n"
"    padding: 8px 10px;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"/* when focused */\n"
"QLineEdit:focus {\n"
"    background-color: #f3f4f6;\n"
"    border: 1px solid #6b7280;\n"
"}\n"
"\n"
"/* disabled */\n"
"QLineEdit:disabled {\n"
"    background-color: #d1d5db;\n"
"    color: #9ca3af;\n"
"}\n"
"")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(370, 210, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(120, 230, 211, 31))
        self.lineEdit_3.setStyleSheet("QLineEdit {\n"
"    background-color: #e5e7eb;      /* light gray */\n"
"    color: #111827;\n"
"    border: 1px solid #d1d5db;\n"
"    border-radius: 12px;            /* smooth border */\n"
"    padding: 8px 10px;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"/* when focused */\n"
"QLineEdit:focus {\n"
"    background-color: #f3f4f6;\n"
"    border: 1px solid #6b7280;\n"
"}\n"
"\n"
"/* disabled */\n"
"QLineEdit:disabled {\n"
"    background-color: #d1d5db;\n"
"    color: #9ca3af;\n"
"}\n"
"")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(130, 60, 241, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(130, 290, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(120, 340, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(120, 360, 471, 31))
        self.lineEdit_4.setStyleSheet("QLineEdit {\n"
"    background-color: #e5e7eb;      /* light gray */\n"
"    color: #111827;\n"
"    border: 1px solid #d1d5db;\n"
"    border-radius: 12px;            /* smooth border */\n"
"    padding: 8px 10px;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"/* when focused */\n"
"QLineEdit:focus {\n"
"    background-color: #f3f4f6;\n"
"    border: 1px solid #6b7280;\n"
"}\n"
"\n"
"/* disabled */\n"
"QLineEdit:disabled {\n"
"    background-color: #d1d5db;\n"
"    color: #9ca3af;\n"
"}\n"
"")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(120, 420, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.lineEdit_5 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(120, 440, 471, 31))
        self.lineEdit_5.setStyleSheet("QLineEdit {\n"
"    background-color: #e5e7eb;      /* light gray */\n"
"    color: #111827;\n"
"    border: 1px solid #d1d5db;\n"
"    border-radius: 12px;            /* smooth border */\n"
"    padding: 8px 10px;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"/* when focused */\n"
"QLineEdit:focus {\n"
"    background-color: #f3f4f6;\n"
"    border: 1px solid #6b7280;\n"
"}\n"
"\n"
"/* disabled */\n"
"QLineEdit:disabled {\n"
"    background-color: #d1d5db;\n"
"    color: #9ca3af;\n"
"}\n"
"")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(70, 50, 47, 31))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("UI\\../../../Downloads/user.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(70, 290, 47, 31))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("UI\\../../../Downloads/lock (1).png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(130, 550, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #2e7d32;        /* Green */\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 12px;\n"
"    padding: 10px 20px;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #43a047;\n"
"    box-shadow: 0px 0px 10px rgba(67, 160, 71, 180);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1b5e20;\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(410, 550, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: #d32f2f;        /* Red */\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 12px;\n"
"    padding: 10px 20px;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #e53935;\n"
"    box-shadow: 0px 0px 10px rgba(229, 57, 53, 180);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #b71c1c;\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "FULL NAME"))
        self.label_2.setText(_translate("MainWindow", "EMAIL ADDRESS"))
        self.label_3.setText(_translate("MainWindow", "CONTACT  NUMBER"))
        self.label_4.setText(_translate("MainWindow", "PERSONAL INFORMATION"))
        self.label_5.setText(_translate("MainWindow", "ACCOUNT SECURITY"))
        self.label_6.setText(_translate("MainWindow", "USERNAME"))
        self.label_7.setText(_translate("MainWindow", "PASSWORD"))
        self.pushButton.setText(_translate("MainWindow", "Create Account"))
        self.pushButton_2.setText(_translate("MainWindow", "Back"))
