# Form implementation generated from reading ui file 'UI/enrollmentDashboard.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1650, 900)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1650, 900))
        MainWindow.setMaximumSize(QtCore.QSize(1650, 900))
        MainWindow.setStyleSheet("#centralwidget {\n"
"    background-color: qlineargradient(\n"
"        spread:pad, x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #eaf3ff,\n"
"        stop:1 #d3e8ff\n"
"    );\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(210, 0, 1441, 121))
        self.widget.setStyleSheet("QWidget {\n"
"    background-color: #eaeaea;  \n"
"    border: 1px solid #cfcfcf;\n"
"    border-radius: 10px;\n"
"}\n"
"")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setGeometry(QtCore.QRect(40, 20, 341, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    background-color: #eaeaea;   /* match your widget color */\n"
"    border: none;                /* remove border */\n"
"    color: #000;                 /* text color (change if needed) */\n"
"}\n"
"")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setGeometry(QtCore.QRect(40, 60, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel {\n"
"    background-color: #eaeaea;   /* match your widget color */\n"
"    border: none;                /* remove border */\n"
"    color: #000;                 /* text color (change if needed) */\n"
"}\n"
"")
        self.label_2.setObjectName("label_2")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_5.setGeometry(QtCore.QRect(1210, 30, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    background-color: #28a745;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    padding: 5px 12px;\n"
"}\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_21 = QtWidgets.QLabel(parent=self.widget)
        self.label_21.setGeometry(QtCore.QRect(1140, 40, 47, 41))
        self.label_21.setStyleSheet("QLabel {\n"
"    border: none;\n"
"    background: transparent;\n"
"}\n"
"")
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap("UI\\../../../Downloads/next.png"))
        self.label_21.setScaledContents(True)
        self.label_21.setObjectName("label_21")
        self.widget_3 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_3.setGeometry(QtCore.QRect(0, 0, 221, 131))
        self.widget_3.setStyleSheet("QWidget {\n"
"    background-color: #eaeaea;  \n"
"    border: 1px solid #cfcfcf;\n"
"    border-radius: 10px;\n"
"}\n"
"")
        self.widget_3.setObjectName("widget_3")
        self.label_3 = QtWidgets.QLabel(parent=self.widget_3)
        self.label_3.setGeometry(QtCore.QRect(20, 30, 51, 51))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("UI\\../../../Downloads/ChatGPT Image Dec 10, 2025, 02_26_54 PM.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.widget_3)
        self.label_4.setGeometry(QtCore.QRect(80, 30, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel {\n"
"    color: #007BFF;    /* nice clean blue */\n"
"    background-color: transparent;   /* optional */\n"
"    border: none;                    /* optional */\n"
"}\n"
"")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.widget_3)
        self.label_5.setGeometry(QtCore.QRect(80, 80, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("QLabel {\n"
"    background-color: #eaeaea;   /* match your widget color */\n"
"    border: none;                /* remove border */\n"
"    color: #000;                 /* text color (change if needed) */\n"
"}\n"
"")
        self.label_5.setObjectName("label_5")
        self.widget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(0, 120, 221, 761))
        self.widget_2.setStyleSheet("QWidget {\n"
"    background-color: #eaeaea;  \n"
"    border: 1px solid #cfcfcf;\n"
"    border-radius: 10px;\n"
"}\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.label_6 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_6.setGeometry(QtCore.QRect(20, 60, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("QLabel {\n"
"    background-color: #eaeaea;   /* match your widget color */\n"
"    border: none;                /* remove border */\n"
"    color: #000;                 /* text color (change if needed) */\n"
"}\n"
"")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("UI\\../../../Downloads/dashboard-monitor.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.pushButton = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton.setGeometry(QtCore.QRect(20, 50, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    outline: none;\n"
"    color: blue;\n"
"}\n"
"QPushButton:hover {\n"
"    color: #1565c0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: #0d47a1;\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.label_7 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_7.setGeometry(QtCore.QRect(30, 140, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("QLabel {\n"
"    background-color: #eaeaea;   /* match your widget color */\n"
"    border: none;                /* remove border */\n"
"    color: #000;                 /* text color (change if needed) */\n"
"}\n"
"")
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("UI\\../../../Downloads/user-add.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 130, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    outline: none;\n"
"    color: blue;\n"
"}\n"
"QPushButton:hover {\n"
"    color: #1565c0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: #0d47a1;\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_8 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_8.setGeometry(QtCore.QRect(20, 210, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("QLabel {\n"
"    background-color: #eaeaea;   /* match your widget color */\n"
"    border: none;                /* remove border */\n"
"    color: #000;                 /* text color (change if needed) */\n"
"}\n"
"")
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("UI\\../../../Downloads/people-group.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 200, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    outline: none;\n"
"    color: blue;\n"
"}\n"
"QPushButton:hover {\n"
"    color: #1565c0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: #0d47a1;\n"
"}\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 700, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setItalic(True)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    outline: none;\n"
"}\n"
"\n"
"QPushButton {\n"
"    color: red;\n"
"}\n"
"\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_9 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_9.setGeometry(QtCore.QRect(30, 710, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("QLabel {\n"
"    background-color: #eaeaea;   /* match your widget color */\n"
"    border: none;                /* remove border */\n"
"    color: #000;                 /* text color (change if needed) */\n"
"}\n"
"")
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("UI\\../../../Downloads/sign-out-alt.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton_6.setGeometry(QtCore.QRect(30, 270, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    outline: none;\n"
"    color: blue;\n"
"}\n"
"QPushButton:hover {\n"
"    color: #1565c0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: #0d47a1;\n"
"}\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_25 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_25.setGeometry(QtCore.QRect(20, 280, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("QLabel {\n"
"    background-color: #eaeaea;   /* match your widget color */\n"
"    border: none;                /* remove border */\n"
"    color: #000;                 /* text color (change if needed) */\n"
"}\n"
"")
        self.label_25.setText("")
        self.label_25.setPixmap(QtGui.QPixmap("UI\\../../../Downloads/credit-card.png"))
        self.label_25.setScaledContents(True)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_26.setGeometry(QtCore.QRect(20, 350, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("QLabel {\n"
"    background-color: #eaeaea;   /* match your widget color */\n"
"    border: none;                /* remove border */\n"
"    color: #000;                 /* text color (change if needed) */\n"
"}\n"
"")
        self.label_26.setText("")
        self.label_26.setPixmap(QtGui.QPixmap("UI\\../../../Downloads/people-group.png"))
        self.label_26.setScaledContents(True)
        self.label_26.setObjectName("label_26")
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton_7.setGeometry(QtCore.QRect(60, 350, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    outline: none;\n"
"    color: blue;\n"
"}\n"
"QPushButton:hover {\n"
"    color: #1565c0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: #0d47a1;\n"
"}\n"
"")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton.raise_()
        self.label_6.raise_()
        self.pushButton_2.raise_()
        self.label_7.raise_()
        self.pushButton_3.raise_()
        self.label_8.raise_()
        self.pushButton_4.raise_()
        self.label_9.raise_()
        self.pushButton_6.raise_()
        self.label_25.raise_()
        self.label_26.raise_()
        self.pushButton_7.raise_()
        self.widget_6 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_6.setGeometry(QtCore.QRect(610, 140, 651, 261))
        self.widget_6.setStyleSheet("QWidget {\n"
"    background-color: #87ceeb;\n"
"    border: 1px solid #7bbcd6;\n"
"    border-radius: 10px;\n"
"}\n"
"")
        self.widget_6.setObjectName("widget_6")
        self.label_10 = QtWidgets.QLabel(parent=self.widget_6)
        self.label_10.setGeometry(QtCore.QRect(60, 30, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(parent=self.widget_6)
        self.label_11.setGeometry(QtCore.QRect(20, 20, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("QLabel {\n"
"    background-color: #eaeaea;   /* match your widget color */\n"
"    border: none;                /* remove border */\n"
"    color: #000;                 /* text color (change if needed) */\n"
"}\n"
"")
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("UI\\../../../Downloads/user (1).png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.textEdit = QtWidgets.QTextEdit(parent=self.widget_6)
        self.textEdit.setGeometry(QtCore.QRect(20, 110, 301, 31))
        self.textEdit.setStyleSheet("QTextEdit {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border: none;\n"
"}\n"
"")
        self.textEdit.setObjectName("textEdit")
        self.label_12 = QtWidgets.QLabel(parent=self.widget_6)
        self.label_12.setGeometry(QtCore.QRect(20, 80, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.label_12.setObjectName("label_12")
        self.textEdit_2 = QtWidgets.QTextEdit(parent=self.widget_6)
        self.textEdit_2.setGeometry(QtCore.QRect(330, 110, 301, 31))
        self.textEdit_2.setStyleSheet("QTextEdit {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border: none;\n"
"}\n"
"")
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_13 = QtWidgets.QLabel(parent=self.widget_6)
        self.label_13.setGeometry(QtCore.QRect(340, 80, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.label_13.setObjectName("label_13")
        self.textEdit_3 = QtWidgets.QTextEdit(parent=self.widget_6)
        self.textEdit_3.setGeometry(QtCore.QRect(20, 190, 301, 31))
        self.textEdit_3.setStyleSheet("QTextEdit {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border: none;\n"
"}\n"
"")
        self.textEdit_3.setObjectName("textEdit_3")
        self.textEdit_4 = QtWidgets.QTextEdit(parent=self.widget_6)
        self.textEdit_4.setGeometry(QtCore.QRect(330, 190, 301, 31))
        self.textEdit_4.setStyleSheet("QTextEdit {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border: none;\n"
"}\n"
"")
        self.textEdit_4.setObjectName("textEdit_4")
        self.label_14 = QtWidgets.QLabel(parent=self.widget_6)
        self.label_14.setGeometry(QtCore.QRect(20, 160, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(parent=self.widget_6)
        self.label_15.setGeometry(QtCore.QRect(340, 160, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.label_15.setObjectName("label_15")
        self.widget_5 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_5.setGeometry(QtCore.QRect(610, 420, 651, 191))
        self.widget_5.setStyleSheet("QWidget {\n"
"    background-color: #87ceeb;\n"
"    border: 1px solid #7bbcd6;\n"
"    border-radius: 10px;\n"
"}\n"
"")
        self.widget_5.setObjectName("widget_5")
        self.label_16 = QtWidgets.QLabel(parent=self.widget_5)
        self.label_16.setGeometry(QtCore.QRect(60, 20, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(parent=self.widget_5)
        self.label_17.setGeometry(QtCore.QRect(20, 10, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("QLabel {\n"
"    background-color: #eaeaea;   /* match your widget color */\n"
"    border: none;                /* remove border */\n"
"    color: #000;                 /* text color (change if needed) */\n"
"}\n"
"")
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap("UI\\../../../Downloads/graduation-cap.png"))
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(parent=self.widget_5)
        self.label_18.setGeometry(QtCore.QRect(30, 60, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.label_18.setObjectName("label_18")
        self.comboBox = QtWidgets.QComboBox(parent=self.widget_5)
        self.comboBox.setGeometry(QtCore.QRect(30, 90, 251, 31))
        self.comboBox.setStyleSheet("QComboBox {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border: none;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: white;\n"
"    color: black;\n"
"}\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_19 = QtWidgets.QLabel(parent=self.widget_5)
        self.label_19.setGeometry(QtCore.QRect(290, 60, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.label_19.setObjectName("label_19")
        self.comboBox_2 = QtWidgets.QComboBox(parent=self.widget_5)
        self.comboBox_2.setGeometry(QtCore.QRect(290, 90, 251, 31))
        self.comboBox_2.setStyleSheet("QComboBox {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border: none;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: white;\n"
"    color: black;\n"
"}\n"
"")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.widget_7 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_7.setGeometry(QtCore.QRect(610, 630, 651, 231))
        self.widget_7.setStyleSheet("QWidget {\n"
"    background-color: #87ceeb;\n"
"    border: 1px solid #7bbcd6;\n"
"    border-radius: 10px;\n"
"}\n"
"")
        self.widget_7.setObjectName("widget_7")
        self.label_20 = QtWidgets.QLabel(parent=self.widget_7)
        self.label_20.setGeometry(QtCore.QRect(30, 20, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.label_20.setObjectName("label_20")
        self.label_22 = QtWidgets.QLabel(parent=self.widget_7)
        self.label_22.setGeometry(QtCore.QRect(30, 60, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.label_22.setObjectName("label_22")
        self.comboBox_3 = QtWidgets.QComboBox(parent=self.widget_7)
        self.comboBox_3.setGeometry(QtCore.QRect(30, 90, 251, 31))
        self.comboBox_3.setStyleSheet("QComboBox {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border: none;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: white;\n"
"    color: black;\n"
"}\n"
"")
        self.comboBox_3.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.comboBox_3.setEditable(False)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.label_23 = QtWidgets.QLabel(parent=self.widget_7)
        self.label_23.setGeometry(QtCore.QRect(300, 60, 191, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.label_23.setObjectName("label_23")
        self.comboBox_4 = QtWidgets.QComboBox(parent=self.widget_7)
        self.comboBox_4.setGeometry(QtCore.QRect(300, 90, 251, 31))
        self.comboBox_4.setStyleSheet("QComboBox {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border: none;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: white;\n"
"    color: black;\n"
"}\n"
"")
        self.comboBox_4.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.comboBox_4.setEditable(False)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.label_24 = QtWidgets.QLabel(parent=self.widget_7)
        self.label_24.setGeometry(QtCore.QRect(30, 140, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.label_24.setObjectName("label_24")
        self.comboBox_5 = QtWidgets.QComboBox(parent=self.widget_7)
        self.comboBox_5.setGeometry(QtCore.QRect(30, 170, 251, 31))
        self.comboBox_5.setStyleSheet("QComboBox {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border: none;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: white;\n"
"    color: black;\n"
"}\n"
"")
        self.comboBox_5.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.comboBox_5.setEditable(False)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Enrollment Management"))
        self.label_2.setText(_translate("MainWindow", "Enroll Student"))
        self.pushButton_5.setText(_translate("MainWindow", "PROCEED"))
        self.label_4.setText(_translate("MainWindow", "EduGate"))
        self.label_5.setText(_translate("MainWindow", "Registrar Portal"))
        self.pushButton.setText(_translate("MainWindow", "Dashboard"))
        self.pushButton_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>Enrollment<br/>Management</p></body></html>"))
        self.pushButton_2.setText(_translate("MainWindow", "Enrollment"))
        self.pushButton_3.setToolTip(_translate("MainWindow", "<html><head/><body><p>Enrollment<br/>Management</p></body></html>"))
        self.pushButton_3.setText(_translate("MainWindow", "Management"))
        self.pushButton_4.setToolTip(_translate("MainWindow", "<html><head/><body><p>Enrollment<br/>Management</p></body></html>"))
        self.pushButton_4.setText(_translate("MainWindow", "Logout"))
        self.pushButton_6.setToolTip(_translate("MainWindow", "<html><head/><body><p>Enrollment<br/>Management</p></body></html>"))
        self.pushButton_6.setText(_translate("MainWindow", "Payment"))
        self.pushButton_7.setToolTip(_translate("MainWindow", "<html><head/><body><p>Enrollment<br/>Management</p></body></html>"))
        self.pushButton_7.setText(_translate("MainWindow", "Slots"))
        self.label_10.setText(_translate("MainWindow", "STUDENT INFORMATION"))
        self.label_12.setText(_translate("MainWindow", "First Name"))
        self.label_13.setText(_translate("MainWindow", "Last Name"))
        self.label_14.setText(_translate("MainWindow", "Email Address"))
        self.label_15.setText(_translate("MainWindow", "Contact Number"))
        self.label_16.setText(_translate("MainWindow", "ACADEMIC DETAILS"))
        self.label_18.setText(_translate("MainWindow", "Grade Level"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Grade 11"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Grade 12"))
        self.label_19.setText(_translate("MainWindow", "Grade Level"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "ABM "))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "HUMSS "))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "STEM "))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "GAS "))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "TVL "))
        self.label_20.setText(_translate("MainWindow", "REQUIRED DOCUMENTS"))
        self.label_22.setText(_translate("MainWindow", "Form 137(Report Card)"))
        self.comboBox_3.setCurrentText(_translate("MainWindow", "Passed"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Passed"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "To-Follow"))
        self.label_23.setText(_translate("MainWindow", "Form 138(Permanent Record)"))
        self.comboBox_4.setCurrentText(_translate("MainWindow", "Passed"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "Passed"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "To-Follow"))
        self.label_24.setText(_translate("MainWindow", "Birth Certificate"))
        self.comboBox_5.setCurrentText(_translate("MainWindow", "Passed"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "Passed"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "To-Follow"))
