# Form implementation generated from reading ui file 'UI/enrollmentReports.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1650, 900)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1650, 900))
        MainWindow.setMaximumSize(QtCore.QSize(1650, 900))
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: white;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(220, 0, 1431, 121))
        self.widget.setStyleSheet("QWidget {\n"
"    background-color: #eaeaea;  \n"
"    border: 1px solid #cfcfcf;\n"
"    border-radius: 10px;\n"
"}\n"
"")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setGeometry(QtCore.QRect(30, 20, 281, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    background-color: #eaeaea;   /* match your widget color */\n"
"    border: none;                /* remove border */\n"
"    color: #000;                 /* text color (change if needed) */\n"
"}\n"
"")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel {\n"
"    background-color: #eaeaea;   /* match your widget color */\n"
"    border: none;                /* remove border */\n"
"    color: #000;                 /* text color (change if needed) */\n"
"}\n"
"")
        self.label_2.setObjectName("label_2")
        self.widget_3 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_3.setGeometry(QtCore.QRect(0, 0, 221, 121))
        self.widget_3.setStyleSheet("QWidget {\n"
"    background-color: #eaeaea;  \n"
"    border: 1px solid #cfcfcf;\n"
"    border-radius: 10px;\n"
"}\n"
"")
        self.widget_3.setObjectName("widget_3")
        self.label_3 = QtWidgets.QLabel(parent=self.widget_3)
        self.label_3.setGeometry(QtCore.QRect(20, 30, 51, 51))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("UI\\../../../Downloads/ChatGPT Image Dec 10, 2025, 02_26_54 PM.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.widget_3)
        self.label_4.setGeometry(QtCore.QRect(80, 30, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel {\n"
"    color: #007BFF;    /* nice clean blue */\n"
"    background-color: transparent;   /* optional */\n"
"    border: none;                    /* optional */\n"
"}\n"
"")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.widget_3)
        self.label_5.setGeometry(QtCore.QRect(20, 80, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("QLabel {\n"
"    background-color: #eaeaea;   /* match your widget color */\n"
"    border: none;                /* remove border */\n"
"    color: #000;                 /* text color (change if needed) */\n"
"}\n"
"")
        self.label_5.setObjectName("label_5")
        self.widget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(0, 120, 221, 761))
        self.widget_2.setStyleSheet("QWidget {\n"
"    background-color: #eaeaea;  \n"
"    border: 1px solid #cfcfcf;\n"
"    border-radius: 10px;\n"
"}\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.label_6 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_6.setGeometry(QtCore.QRect(20, 60, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("QLabel {\n"
"    background-color: #eaeaea;   /* match your widget color */\n"
"    border: none;                /* remove border */\n"
"    color: #000;                 /* text color (change if needed) */\n"
"}\n"
"")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("UI\\../../../Downloads/dashboard-monitor.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.pushButton = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton.setGeometry(QtCore.QRect(30, 60, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    outline: none;\n"
"    color: blue;\n"
"}\n"
"QPushButton:hover {\n"
"    color: #1565c0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: #0d47a1;\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.label_7 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_7.setGeometry(QtCore.QRect(30, 140, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("QLabel {\n"
"    background-color: #eaeaea;   /* match your widget color */\n"
"    border: none;                /* remove border */\n"
"    color: #000;                 /* text color (change if needed) */\n"
"}\n"
"")
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("UI\\../../../Downloads/user-add.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton_2.setGeometry(QtCore.QRect(70, 140, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    outline: none;\n"
"    color: blue;\n"
"}\n"
"QPushButton:hover {\n"
"    color: #1565c0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: #0d47a1;\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_8 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_8.setGeometry(QtCore.QRect(20, 260, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("QLabel {\n"
"    background-color: #eaeaea;   /* match your widget color */\n"
"    border: none;                /* remove border */\n"
"    color: #000;                 /* text color (change if needed) */\n"
"}\n"
"")
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("UI\\../../../Downloads/people-group.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 270, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    outline: none;\n"
"    color: blue;\n"
"}\n"
"QPushButton:hover {\n"
"    color: #1565c0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: #0d47a1;\n"
"}\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 700, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setItalic(True)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    outline: none;\n"
"}\n"
"\n"
"QPushButton {\n"
"    color: red;\n"
"}\n"
"\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_9 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_9.setGeometry(QtCore.QRect(30, 710, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("QLabel {\n"
"    background-color: #eaeaea;   /* match your widget color */\n"
"    border: none;                /* remove border */\n"
"    color: #000;                 /* text color (change if needed) */\n"
"}\n"
"")
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("UI\\../../../Downloads/sign-out-alt.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton_6.setGeometry(QtCore.QRect(60, 210, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    outline: none;\n"
"    color: blue;\n"
"}\n"
"QPushButton:hover {\n"
"    color: #1565c0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: #0d47a1;\n"
"}\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_11 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_11.setGeometry(QtCore.QRect(20, 210, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("QLabel {\n"
"    background-color: #eaeaea;   /* match your widget color */\n"
"    border: none;                /* remove border */\n"
"    color: #000;                 /* text color (change if needed) */\n"
"}\n"
"")
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("UI\\../../../Downloads/people-group.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.pushButton.raise_()
        self.label_6.raise_()
        self.pushButton_2.raise_()
        self.label_7.raise_()
        self.pushButton_3.raise_()
        self.label_8.raise_()
        self.pushButton_4.raise_()
        self.label_9.raise_()
        self.pushButton_6.raise_()
        self.label_11.raise_()
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(420, 240, 1081, 501))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(178)
        self.label_10 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(420, 210, 391, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(420, 750, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    background-color: #007BFF;  /* Blue background */\n"
"    color: white;               /* White text */\n"
"    border: none;               /* No border */\n"
"    border-radius: 6px;         /* Rounded corners */\n"
"    padding: 5px 12px;          /* Optional padding */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0056b3;  /* Darker blue on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #00408d;  /* Even darker blue when pressed */\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Reports"))
        self.label_2.setText(_translate("MainWindow", "Control Area"))
        self.label_4.setText(_translate("MainWindow", "EduGate"))
        self.label_5.setText(_translate("MainWindow", "Admin Panel"))
        self.pushButton.setText(_translate("MainWindow", "Dashboard"))
        self.pushButton_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>Enrollment<br/>Management</p></body></html>"))
        self.pushButton_2.setText(_translate("MainWindow", "User Management"))
        self.pushButton_3.setToolTip(_translate("MainWindow", "<html><head/><body><p>Enrollment<br/>Management</p></body></html>"))
        self.pushButton_3.setText(_translate("MainWindow", "Reports"))
        self.pushButton_4.setToolTip(_translate("MainWindow", "<html><head/><body><p>Enrollment<br/>Management</p></body></html>"))
        self.pushButton_4.setText(_translate("MainWindow", "Logout"))
        self.pushButton_6.setToolTip(_translate("MainWindow", "<html><head/><body><p>Enrollment<br/>Management</p></body></html>"))
        self.pushButton_6.setText(_translate("MainWindow", "Enrollment Reports"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "STUDENT ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "NAME"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "YEAR"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "STRAND"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "SCHEDULE"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "REGISTRAR"))
        self.label_10.setText(_translate("MainWindow", "ENROLLMENT REPORTS PER STUDENT"))
        self.pushButton_5.setText(_translate("MainWindow", "Download All Reports"))
