# Form implementation generated from reading ui file 'UI/registrarDashboard.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1650, 900)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1650, 900))
        MainWindow.setMaximumSize(QtCore.QSize(1650, 900))
        MainWindow.setStyleSheet("#centralwidget {\n"
"    background-color: qlineargradient(\n"
"        spread:pad, x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #eaf3ff,\n"
"        stop:1 #d3e8ff\n"
"    );\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(210, 0, 1451, 121))
        self.widget.setStyleSheet("QWidget {\n"
"    background-color: #eaeaea;  \n"
"    border: 1px solid #cfcfcf;\n"
"    border-radius: 10px;\n"
"}\n"
"")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setGeometry(QtCore.QRect(50, 20, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    background-color: #eaeaea;   /* match your widget color */\n"
"    border: none;                /* remove border */\n"
"    color: #000;                 /* text color (change if needed) */\n"
"}\n"
"")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setGeometry(QtCore.QRect(50, 60, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel {\n"
"    background-color: #eaeaea;   /* match your widget color */\n"
"    border: none;                /* remove border */\n"
"    color: #000;                 /* text color (change if needed) */\n"
"}\n"
"")
        self.label_2.setObjectName("label_2")
        self.widget_3 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_3.setGeometry(QtCore.QRect(-20, 0, 241, 131))
        self.widget_3.setStyleSheet("QWidget {\n"
"    background-color: #eaeaea;  \n"
"    border: 1px solid #cfcfcf;\n"
"    border-radius: 10px;\n"
"}\n"
"")
        self.widget_3.setObjectName("widget_3")
        self.label_3 = QtWidgets.QLabel(parent=self.widget_3)
        self.label_3.setGeometry(QtCore.QRect(40, 30, 51, 51))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("UI\\../../../Downloads/ChatGPT Image Dec 10, 2025, 02_26_54 PM.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.widget_3)
        self.label_4.setGeometry(QtCore.QRect(100, 20, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel {\n"
"    color: #007BFF;    /* nice clean blue */\n"
"    background-color: transparent;   /* optional */\n"
"    border: none;                    /* optional */\n"
"}\n"
"")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.widget_3)
        self.label_5.setGeometry(QtCore.QRect(100, 60, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("QLabel {\n"
"    background-color: #eaeaea;   /* match your widget color */\n"
"    border: none;                /* remove border */\n"
"    color: #000;                 /* text color (change if needed) */\n"
"}\n"
"")
        self.label_5.setObjectName("label_5")
        self.widget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(0, 120, 221, 771))
        self.widget_2.setStyleSheet("QWidget {\n"
"    background-color: #eaeaea;  \n"
"    border: 1px solid #cfcfcf;\n"
"    border-radius: 10px;\n"
"}\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.label_6 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_6.setGeometry(QtCore.QRect(20, 60, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("QLabel {\n"
"    background-color: #eaeaea;   /* match your widget color */\n"
"    border: none;                /* remove border */\n"
"    color: #000;                 /* text color (change if needed) */\n"
"}\n"
"")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("UI\\../../../Downloads/dashboard-monitor.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.pushButton = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton.setGeometry(QtCore.QRect(20, 50, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    outline: none;\n"
"    color: blue;\n"
"}\n"
"QPushButton:hover {\n"
"    color: #1565c0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: #0d47a1;\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.label_7 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_7.setGeometry(QtCore.QRect(30, 140, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("QLabel {\n"
"    background-color: #eaeaea;   /* match your widget color */\n"
"    border: none;                /* remove border */\n"
"    color: #000;                 /* text color (change if needed) */\n"
"}\n"
"")
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("UI\\../../../Downloads/user-add.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 130, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    outline: none;\n"
"    color: blue;\n"
"}\n"
"QPushButton:hover {\n"
"    color: #1565c0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: #0d47a1;\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_8 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_8.setGeometry(QtCore.QRect(20, 210, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("QLabel {\n"
"    background-color: #eaeaea;   /* match your widget color */\n"
"    border: none;                /* remove border */\n"
"    color: #000;                 /* text color (change if needed) */\n"
"}\n"
"")
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("UI\\../../../Downloads/people-group.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 200, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    outline: none;\n"
"    color: blue;\n"
"}\n"
"QPushButton:hover {\n"
"    color: #1565c0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: #0d47a1;\n"
"}\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 700, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    outline: none;\n"
"}\n"
"\n"
"QPushButton {\n"
"    color: red;\n"
"}\n"
"\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_9 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_9.setGeometry(QtCore.QRect(30, 710, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("QLabel {\n"
"    background-color: #eaeaea;   /* match your widget color */\n"
"    border: none;                /* remove border */\n"
"    color: #000;                 /* text color (change if needed) */\n"
"}\n"
"")
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("UI\\../../../Downloads/sign-out-alt.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton_6.setGeometry(QtCore.QRect(20, 270, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    outline: none;\n"
"    color: blue;\n"
"}\n"
"QPushButton:hover {\n"
"    color: #1565c0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: #0d47a1;\n"
"}\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_11 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_11.setGeometry(QtCore.QRect(20, 280, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("QLabel {\n"
"    background-color: #eaeaea;   /* match your widget color */\n"
"    border: none;                /* remove border */\n"
"    color: #000;                 /* text color (change if needed) */\n"
"}\n"
"")
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("UI\\../../../Downloads/credit-card.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.label_13 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_13.setGeometry(QtCore.QRect(20, 360, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("QLabel {\n"
"    background-color: #eaeaea;   /* match your widget color */\n"
"    border: none;                /* remove border */\n"
"    color: #000;                 /* text color (change if needed) */\n"
"}\n"
"")
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("UI\\../../../Downloads/people-group.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton_5.setGeometry(QtCore.QRect(60, 360, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    outline: none;\n"
"    color: blue;\n"
"}\n"
"QPushButton:hover {\n"
"    color: #1565c0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: #0d47a1;\n"
"}\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton.raise_()
        self.label_6.raise_()
        self.pushButton_2.raise_()
        self.label_7.raise_()
        self.pushButton_3.raise_()
        self.label_8.raise_()
        self.pushButton_4.raise_()
        self.label_9.raise_()
        self.pushButton_6.raise_()
        self.label_11.raise_()
        self.label_13.raise_()
        self.pushButton_5.raise_()
        self.widget_6 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_6.setGeometry(QtCore.QRect(300, 140, 411, 231))
        self.widget_6.setStyleSheet("QWidget {\n"
"    background-color: #eaeaea;  \n"
"    border: 1px solid #cfcfcf;\n"
"    border-radius: 10px;\n"
"}\n"
"")
        self.widget_6.setObjectName("widget_6")
        self.label_10 = QtWidgets.QLabel(parent=self.widget_6)
        self.label_10.setGeometry(QtCore.QRect(30, 20, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("QLabel {\n"
"    background-color: #eaeaea;   /* match your widget color */\n"
"    border: none;                /* remove border */\n"
"    color: #000;                 /* text color (change if needed) */\n"
"}\n"
"")
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("UI\\../../../Downloads/check-mark_12503776.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.label_16 = QtWidgets.QLabel(parent=self.widget_6)
        self.label_16.setGeometry(QtCore.QRect(40, 140, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("QLabel {\n"
"    background-color: #eaeaea;   /* match your widget color */\n"
"    border: none;                /* remove border */\n"
"    color: #000;                 /* text color (change if needed) */\n"
"}\n"
"")
        self.label_16.setObjectName("label_16")
        self.btnVerified = QtWidgets.QPushButton(parent=self.widget_6)
        self.btnVerified.setGeometry(QtCore.QRect(20, 80, 251, 23))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btnVerified.setFont(font)
        self.btnVerified.setStyleSheet("QPushButton {\n"
"    background-color: #eaeaea;   /* match your widget color */\n"
"    border: none;                /* remove border */\n"
"    color: #000;                 /* text color (change if needed) */\n"
"}\n"
"")
        self.btnVerified.setObjectName("btnVerified")
        self.widget_5 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_5.setGeometry(QtCore.QRect(750, 140, 391, 231))
        self.widget_5.setStyleSheet("QWidget {\n"
"    background-color: #eaeaea;  \n"
"    border: 1px solid #cfcfcf;\n"
"    border-radius: 10px;\n"
"}\n"
"")
        self.widget_5.setObjectName("widget_5")
        self.label_12 = QtWidgets.QLabel(parent=self.widget_5)
        self.label_12.setGeometry(QtCore.QRect(20, 20, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("QLabel {\n"
"    background-color: #eaeaea;   /* match your widget color */\n"
"    border: none;                /* remove border */\n"
"    color: #000;                 /* text color (change if needed) */\n"
"}\n"
"")
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("UI\\../../../Downloads/agreement_14251593.png"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.label_17 = QtWidgets.QLabel(parent=self.widget_5)
        self.label_17.setGeometry(QtCore.QRect(50, 130, 281, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("QLabel {\n"
"    background-color: #eaeaea;   /* match your widget color */\n"
"    border: none;                /* remove border */\n"
"    color: #000;                 /* text color (change if needed) */\n"
"}\n"
"")
        self.label_17.setObjectName("label_17")
        self.btnToFollow = QtWidgets.QPushButton(parent=self.widget_5)
        self.btnToFollow.setGeometry(QtCore.QRect(50, 80, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btnToFollow.setFont(font)
        self.btnToFollow.setStyleSheet("QPushButton {\n"
"    background-color: #eaeaea;   /* match your widget color */\n"
"    border: none;                /* remove border */\n"
"    color: #000;                 /* text color (change if needed) */\n"
"}\n"
"")
        self.btnToFollow.setObjectName("btnToFollow")
        self.widget_7 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_7.setGeometry(QtCore.QRect(1180, 140, 401, 231))
        self.widget_7.setStyleSheet("QWidget {\n"
"    background-color: #eaeaea;  \n"
"    border: 1px solid #cfcfcf;\n"
"    border-radius: 10px;\n"
"}\n"
"")
        self.widget_7.setObjectName("widget_7")
        self.label_14 = QtWidgets.QLabel(parent=self.widget_7)
        self.label_14.setGeometry(QtCore.QRect(20, 20, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("QLabel {\n"
"    background-color: #eaeaea;   /* match your widget color */\n"
"    border: none;                /* remove border */\n"
"    color: #000;                 /* text color (change if needed) */\n"
"}\n"
"")
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("UI\\../../../Downloads/groups_7235322.png"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.label_18 = QtWidgets.QLabel(parent=self.widget_7)
        self.label_18.setGeometry(QtCore.QRect(50, 140, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("QLabel {\n"
"    background-color: #eaeaea;   /* match your widget color */\n"
"    border: none;                /* remove border */\n"
"    color: #000;                 /* text color (change if needed) */\n"
"}\n"
"")
        self.label_18.setObjectName("label_18")
        self.btnEnrolled = QtWidgets.QPushButton(parent=self.widget_7)
        self.btnEnrolled.setGeometry(QtCore.QRect(30, 80, 261, 23))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btnEnrolled.setFont(font)
        self.btnEnrolled.setStyleSheet("QPushButton {\n"
"    background-color: #eaeaea;   /* match your widget color */\n"
"    border: none;                /* remove border */\n"
"    color: #000;                 /* text color (change if needed) */\n"
"}\n"
"")
        self.btnEnrolled.setObjectName("btnEnrolled")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Dashboard"))
        self.label_2.setText(_translate("MainWindow", "Welcome back, Registrar"))
        self.label_4.setText(_translate("MainWindow", "EduGate"))
        self.label_5.setText(_translate("MainWindow", "Registrar Portal"))
        self.pushButton.setText(_translate("MainWindow", "Dashboard"))
        self.pushButton_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>Enrollment<br/>Management</p></body></html>"))
        self.pushButton_2.setText(_translate("MainWindow", "Enrollment"))
        self.pushButton_3.setToolTip(_translate("MainWindow", "<html><head/><body><p>Enrollment<br/>Management</p></body></html>"))
        self.pushButton_3.setText(_translate("MainWindow", "Management"))
        self.pushButton_4.setToolTip(_translate("MainWindow", "<html><head/><body><p>Enrollment<br/>Management</p></body></html>"))
        self.pushButton_4.setText(_translate("MainWindow", "Logout"))
        self.pushButton_6.setToolTip(_translate("MainWindow", "<html><head/><body><p>Enrollment<br/>Management</p></body></html>"))
        self.pushButton_6.setText(_translate("MainWindow", "Payment"))
        self.pushButton_5.setToolTip(_translate("MainWindow", "<html><head/><body><p>Enrollment<br/>Management</p></body></html>"))
        self.pushButton_5.setText(_translate("MainWindow", "Slots"))
        self.label_16.setText(_translate("MainWindow", "Verified Students"))
        self.btnVerified.setText(_translate("MainWindow", "Verified Students"))
        self.label_17.setText(_translate("MainWindow", "To-Follow Documents"))
        self.btnToFollow.setText(_translate("MainWindow", "To-Follow Documents"))
        self.label_18.setText(_translate("MainWindow", "Enrolled Students"))
        self.btnEnrolled.setText(_translate("MainWindow", "Enrolled Students"))
