# Form implementation generated from reading ui file 'UI/stem12.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1650, 900)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1650, 900))
        MainWindow.setMaximumSize(QtCore.QSize(1650, 900))
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: white;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(210, 0, 1441, 121))
        self.widget.setStyleSheet("QWidget {\n"
"    background-color: #eaeaea;  \n"
"    border: 1px solid #cfcfcf;\n"
"    border-radius: 10px;\n"
"}\n"
"")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setGeometry(QtCore.QRect(30, 20, 341, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    background-color: #eaeaea;   /* match your widget color */\n"
"    border: none;                /* remove border */\n"
"    color: #000;                 /* text color (change if needed) */\n"
"}\n"
"")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel {\n"
"    background-color: #eaeaea;   /* match your widget color */\n"
"    border: none;                /* remove border */\n"
"    color: #000;                 /* text color (change if needed) */\n"
"}\n"
"")
        self.label_2.setObjectName("label_2")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_5.setGeometry(QtCore.QRect(1210, 30, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    background-color: #28a745;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    padding: 5px 12px;\n"
"}\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.widget_3 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_3.setGeometry(QtCore.QRect(0, 0, 221, 131))
        self.widget_3.setStyleSheet("QWidget {\n"
"    background-color: #eaeaea;  \n"
"    border: 1px solid #cfcfcf;\n"
"    border-radius: 10px;\n"
"}\n"
"")
        self.widget_3.setObjectName("widget_3")
        self.label_3 = QtWidgets.QLabel(parent=self.widget_3)
        self.label_3.setGeometry(QtCore.QRect(20, 30, 51, 51))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("UI\\../../../Downloads/ChatGPT Image Dec 10, 2025, 02_26_54 PM.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.widget_3)
        self.label_4.setGeometry(QtCore.QRect(80, 30, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel {\n"
"    color: #007BFF;    /* nice clean blue */\n"
"    background-color: transparent;   /* optional */\n"
"    border: none;                    /* optional */\n"
"}\n"
"")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.widget_3)
        self.label_5.setGeometry(QtCore.QRect(80, 80, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("QLabel {\n"
"    background-color: #eaeaea;   /* match your widget color */\n"
"    border: none;                /* remove border */\n"
"    color: #000;                 /* text color (change if needed) */\n"
"}\n"
"")
        self.label_5.setObjectName("label_5")
        self.widget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(0, 120, 221, 761))
        self.widget_2.setStyleSheet("QWidget {\n"
"    background-color: #eaeaea;  \n"
"    border: 1px solid #cfcfcf;\n"
"    border-radius: 10px;\n"
"}\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.label_6 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_6.setGeometry(QtCore.QRect(20, 60, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("QLabel {\n"
"    background-color: #eaeaea;   /* match your widget color */\n"
"    border: none;                /* remove border */\n"
"    color: #000;                 /* text color (change if needed) */\n"
"}\n"
"")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("UI\\../../../Downloads/dashboard-monitor.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.pushButton = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton.setGeometry(QtCore.QRect(20, 50, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    outline: none;\n"
"    color: blue;\n"
"}\n"
"QPushButton:hover {\n"
"    color: #1565c0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: #0d47a1;\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.label_7 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_7.setGeometry(QtCore.QRect(30, 140, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("QLabel {\n"
"    background-color: #eaeaea;   /* match your widget color */\n"
"    border: none;                /* remove border */\n"
"    color: #000;                 /* text color (change if needed) */\n"
"}\n"
"")
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("UI\\../../../Downloads/user-add.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 130, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    outline: none;\n"
"    color: blue;\n"
"}\n"
"QPushButton:hover {\n"
"    color: #1565c0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: #0d47a1;\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_8 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_8.setGeometry(QtCore.QRect(20, 210, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("QLabel {\n"
"    background-color: #eaeaea;   /* match your widget color */\n"
"    border: none;                /* remove border */\n"
"    color: #000;                 /* text color (change if needed) */\n"
"}\n"
"")
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("UI\\../../../Downloads/people-group.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 200, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    outline: none;\n"
"    color: blue;\n"
"}\n"
"QPushButton:hover {\n"
"    color: #1565c0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: #0d47a1;\n"
"}\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 700, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setItalic(True)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    outline: none;\n"
"}\n"
"\n"
"QPushButton {\n"
"    color: red;\n"
"}\n"
"\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_9 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_9.setGeometry(QtCore.QRect(30, 710, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("QLabel {\n"
"    background-color: #eaeaea;   /* match your widget color */\n"
"    border: none;                /* remove border */\n"
"    color: #000;                 /* text color (change if needed) */\n"
"}\n"
"")
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("UI\\../../../Downloads/sign-out-alt.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton_6.setGeometry(QtCore.QRect(20, 260, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    outline: none;\n"
"    color: blue;\n"
"}\n"
"QPushButton:hover {\n"
"    color: #1565c0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: #0d47a1;\n"
"}\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_11 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_11.setGeometry(QtCore.QRect(20, 270, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("QLabel {\n"
"    background-color: #eaeaea;   /* match your widget color */\n"
"    border: none;                /* remove border */\n"
"    color: #000;                 /* text color (change if needed) */\n"
"}\n"
"")
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("UI\\../../../Downloads/credit-card.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.pushButton.raise_()
        self.label_6.raise_()
        self.pushButton_2.raise_()
        self.label_7.raise_()
        self.pushButton_3.raise_()
        self.label_8.raise_()
        self.pushButton_4.raise_()
        self.label_9.raise_()
        self.pushButton_6.raise_()
        self.label_11.raise_()
        self.widget_7 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_7.setGeometry(QtCore.QRect(590, 140, 651, 681))
        self.widget_7.setStyleSheet("QWidget {\n"
"    background-color: #87ceeb;\n"
"    border: 1px solid #7bbcd6;\n"
"    border-radius: 10px;\n"
"}\n"
"")
        self.widget_7.setObjectName("widget_7")
        self.label_20 = QtWidgets.QLabel(parent=self.widget_7)
        self.label_20.setGeometry(QtCore.QRect(100, 30, 471, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.label_20.setObjectName("label_20")
        self.label_22 = QtWidgets.QLabel(parent=self.widget_7)
        self.label_22.setGeometry(QtCore.QRect(50, 170, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.label_22.setObjectName("label_22")
        self.comboBox_3 = QtWidgets.QComboBox(parent=self.widget_7)
        self.comboBox_3.setGeometry(QtCore.QRect(50, 210, 251, 31))
        self.comboBox_3.setStyleSheet("QComboBox {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border: none;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: white;\n"
"    color: black;\n"
"}\n"
"")
        self.comboBox_3.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.comboBox_3.setEditable(False)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.label_23 = QtWidgets.QLabel(parent=self.widget_7)
        self.label_23.setGeometry(QtCore.QRect(350, 170, 191, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.label_23.setObjectName("label_23")
        self.comboBox_4 = QtWidgets.QComboBox(parent=self.widget_7)
        self.comboBox_4.setGeometry(QtCore.QRect(350, 210, 251, 31))
        self.comboBox_4.setStyleSheet("QComboBox {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border: none;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: white;\n"
"    color: black;\n"
"}\n"
"")
        self.comboBox_4.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.comboBox_4.setEditable(False)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_5 = QtWidgets.QComboBox(parent=self.widget_7)
        self.comboBox_5.setGeometry(QtCore.QRect(50, 320, 251, 31))
        self.comboBox_5.setStyleSheet("QComboBox {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border: none;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: white;\n"
"    color: black;\n"
"}\n"
"")
        self.comboBox_5.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.comboBox_5.setEditable(False)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.label_25 = QtWidgets.QLabel(parent=self.widget_7)
        self.label_25.setGeometry(QtCore.QRect(50, 280, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.label_25.setObjectName("label_25")
        self.comboBox_6 = QtWidgets.QComboBox(parent=self.widget_7)
        self.comboBox_6.setGeometry(QtCore.QRect(350, 320, 251, 31))
        self.comboBox_6.setStyleSheet("QComboBox {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border: none;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: white;\n"
"    color: black;\n"
"}\n"
"")
        self.comboBox_6.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.comboBox_6.setEditable(False)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.label_26 = QtWidgets.QLabel(parent=self.widget_7)
        self.label_26.setGeometry(QtCore.QRect(350, 280, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.label_26.setObjectName("label_26")
        self.checkBox = QtWidgets.QCheckBox(parent=self.widget_7)
        self.checkBox.setGeometry(QtCore.QRect(90, 500, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox.setFont(font)
        self.checkBox.setStyleSheet("QCheckBox {\n"
"    background: transparent;\n"
"    border: none;\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"\n"
"    spacing: 10px;\n"
"    color: #000000;          /* BLACK text */\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border: none;            /* no border */\n"
"    background-color: #e5e7eb;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #22c55e;   /* green */\n"
"}\n"
"")
        self.checkBox.setObjectName("checkBox")
        self.checkBox_3 = QtWidgets.QCheckBox(parent=self.widget_7)
        self.checkBox_3.setGeometry(QtCore.QRect(440, 500, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setStyleSheet("QCheckBox {\n"
"    background: transparent;\n"
"    border: none;\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"\n"
"    spacing: 10px;\n"
"    color: #000000;          /* BLACK text */\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border: none;            /* no border */\n"
"    background-color: #e5e7eb;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #22c55e;   /* green */\n"
"}\n"
"")
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(parent=self.widget_7)
        self.checkBox_4.setGeometry(QtCore.QRect(270, 500, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setStyleSheet("QCheckBox {\n"
"    background: transparent;\n"
"    border: none;\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"\n"
"    spacing: 10px;\n"
"    color: #000000;          /* BLACK text */\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border: none;            /* no border */\n"
"    background-color: #e5e7eb;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #22c55e;   /* green */\n"
"}\n"
"")
        self.checkBox_4.setObjectName("checkBox_4")
        self.label_34 = QtWidgets.QLabel(parent=self.widget_7)
        self.label_34.setGeometry(QtCore.QRect(270, 470, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.label_34.setObjectName("label_34")
        self.label_28 = QtWidgets.QLabel(parent=self.widget_7)
        self.label_28.setGeometry(QtCore.QRect(210, 100, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.label_28.setObjectName("label_28")
        self.comboBox_7 = QtWidgets.QComboBox(parent=self.widget_7)
        self.comboBox_7.setGeometry(QtCore.QRect(200, 410, 251, 31))
        self.comboBox_7.setStyleSheet("QComboBox {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border: none;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: white;\n"
"    color: black;\n"
"}\n"
"")
        self.comboBox_7.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.comboBox_7.setEditable(False)
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.label_27 = QtWidgets.QLabel(parent=self.widget_7)
        self.label_27.setGeometry(QtCore.QRect(250, 380, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.label_27.setObjectName("label_27")
        self.label_35 = QtWidgets.QLabel(parent=self.widget_7)
        self.label_35.setGeometry(QtCore.QRect(270, 560, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.label_35.setObjectName("label_35")
        self.checkBox_5 = QtWidgets.QCheckBox(parent=self.widget_7)
        self.checkBox_5.setGeometry(QtCore.QRect(90, 580, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_5.setFont(font)
        self.checkBox_5.setStyleSheet("QCheckBox {\n"
"    background: transparent;\n"
"    border: none;\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"\n"
"    spacing: 10px;\n"
"    color: #000000;          /* BLACK text */\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border: none;            /* no border */\n"
"    background-color: #e5e7eb;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #22c55e;   /* green */\n"
"}\n"
"")
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(parent=self.widget_7)
        self.checkBox_6.setGeometry(QtCore.QRect(260, 580, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_6.setFont(font)
        self.checkBox_6.setStyleSheet("QCheckBox {\n"
"    background: transparent;\n"
"    border: none;\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"\n"
"    spacing: 10px;\n"
"    color: #000000;          /* BLACK text */\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border: none;            /* no border */\n"
"    background-color: #e5e7eb;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #22c55e;   /* green */\n"
"}\n"
"")
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_7 = QtWidgets.QCheckBox(parent=self.widget_7)
        self.checkBox_7.setGeometry(QtCore.QRect(440, 580, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_7.setFont(font)
        self.checkBox_7.setStyleSheet("QCheckBox {\n"
"    background: transparent;\n"
"    border: none;\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"\n"
"    spacing: 10px;\n"
"    color: #000000;          /* BLACK text */\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border: none;            /* no border */\n"
"    background-color: #e5e7eb;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #22c55e;   /* green */\n"
"}\n"
"")
        self.checkBox_7.setObjectName("checkBox_7")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Enrollment Management"))
        self.label_2.setText(_translate("MainWindow", "Enroll Student"))
        self.pushButton_5.setText(_translate("MainWindow", "NEXT"))
        self.label_4.setText(_translate("MainWindow", "EduGate"))
        self.label_5.setText(_translate("MainWindow", "Registrar Portal"))
        self.pushButton.setText(_translate("MainWindow", "Dashboard"))
        self.pushButton_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>Enrollment<br/>Management</p></body></html>"))
        self.pushButton_2.setText(_translate("MainWindow", "Enrollment"))
        self.pushButton_3.setToolTip(_translate("MainWindow", "<html><head/><body><p>Enrollment<br/>Management</p></body></html>"))
        self.pushButton_3.setText(_translate("MainWindow", "Management"))
        self.pushButton_4.setToolTip(_translate("MainWindow", "<html><head/><body><p>Enrollment<br/>Management</p></body></html>"))
        self.pushButton_4.setText(_translate("MainWindow", "Logout"))
        self.pushButton_6.setToolTip(_translate("MainWindow", "<html><head/><body><p>Enrollment<br/>Management</p></body></html>"))
        self.pushButton_6.setText(_translate("MainWindow", "Payment"))
        self.label_20.setText(_translate("MainWindow", "ASSIGNING OF TEACHERS AND SECTIONS"))
        self.label_22.setText(_translate("MainWindow", "GENERAL BIOLOGY 2"))
        self.comboBox_3.setCurrentText(_translate("MainWindow", "SELECT TEACHER"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "SELECT TEACHER"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Victor A. Tan"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "Catherine L. Uy"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "Paolo R. Navarro"))
        self.label_23.setText(_translate("MainWindow", "GENERAL CHEMISTRY 2"))
        self.comboBox_4.setCurrentText(_translate("MainWindow", "SELECT TEACHER"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "SELECT TEACHER"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "Carl J. Mendoza"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "Janine F. Dela Cruz"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "Arvin S. Bautista"))
        self.comboBox_5.setCurrentText(_translate("MainWindow", "SELECT TEACHER"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "SELECT TEACHER"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "Mark J. Rivera"))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "Andrew M. Lim"))
        self.comboBox_5.setItemText(3, _translate("MainWindow", "Clarissa M. Villanueva"))
        self.label_25.setText(_translate("MainWindow", "GENERAL PHYSICS 2"))
        self.comboBox_6.setCurrentText(_translate("MainWindow", "SELECT TEACHER"))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "SELECT TEACHER"))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "Joseph L. Mendoza"))
        self.comboBox_6.setItemText(2, _translate("MainWindow", "Patricia L. Gomez"))
        self.comboBox_6.setItemText(3, _translate("MainWindow", "Andrea L. Perez"))
        self.label_26.setText(_translate("MainWindow", "RESEARCH / CAPSTONE"))
        self.checkBox.setText(_translate("MainWindow", "STEM12 - 1"))
        self.checkBox_3.setText(_translate("MainWindow", "STEM12 - 3"))
        self.checkBox_4.setText(_translate("MainWindow", "STEM12 - 2"))
        self.label_34.setText(_translate("MainWindow", "SECTIONS"))
        self.label_28.setText(_translate("MainWindow", "TEACHERS - STEM 12"))
        self.comboBox_7.setCurrentText(_translate("MainWindow", "SELECT TEACHER"))
        self.comboBox_7.setItemText(0, _translate("MainWindow", "SELECT TEACHER"))
        self.comboBox_7.setItemText(1, _translate("MainWindow", "Roberto D. Santos"))
        self.comboBox_7.setItemText(2, _translate("MainWindow", "Maria K. Ramos"))
        self.comboBox_7.setItemText(3, _translate("MainWindow", "Jonathan P. Reyes"))
        self.label_27.setText(_translate("MainWindow", "BASIC CALCULUS"))
        self.label_35.setText(_translate("MainWindow", "SCHEDULE"))
        self.checkBox_5.setText(_translate("MainWindow", "MORNING"))
        self.checkBox_6.setText(_translate("MainWindow", "AFTERNOON"))
        self.checkBox_7.setText(_translate("MainWindow", "EVENING"))
